export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const FETCH_GAMES = "FETCH_GAMES";
export const CHAT_LOADING = "CHAT_LOADING";
