export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_USER_HISTORY = "SET_USER_HISTORY";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const CHAT_LOADING = "CHAT_LOADING";

export const LOAD_GAMES = "LOAD_GAMES";
export const LOAD_NEW_GAME = "LOAD_NEW_GAME";
export const UNLOAD_GAME = "UNLOAD_GAME";
export const TAVERN_LOADING = "TAVERN_LOADING";
export const CLEAR_GAMES = "CLEAR_GAMES";

export const SET_CURRENT_GAME = "SET_CURRENT_GAME";
